# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

def fib_numbers(first, second, total):
    third = first + second
    if third >= 4000000:
        print(total)
    else:
        if third % 2 == 0:
            total += third
        return fib_numbers(second,third,total)

fib_numbers(0,1,0)
